[2024-04-27T18:33:30.141+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T18:33:30.158+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:32:26.190012+00:00 [queued]>
[2024-04-27T18:33:30.163+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:32:26.190012+00:00 [queued]>
[2024-04-27T18:33:30.163+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2024-04-27T18:33:30.173+0000] {taskinstance.py:2327} INFO - Executing <Task(DockerOperator): el_spotify> on 2024-04-27 18:32:26.190012+00:00
[2024-04-27T18:33:30.179+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T18:33:30.180+0000] {standard_task_runner.py:63} INFO - Started process 97 to run task
[2024-04-27T18:33:30.180+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_extract_dag', 'el_spotify', 'manual__2024-04-27T18:32:26.190012+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/meltano_spotify_dag.py', '--cfg-path', '/tmp/tmp0_7oervw']
[2024-04-27T18:33:30.181+0000] {standard_task_runner.py:91} INFO - Job 149: Subtask el_spotify
[2024-04-27T18:33:30.211+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:32:26.190012+00:00 [running]> on host dab0fcf0ce12
[2024-04-27T18:33:30.275+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_extract_dag' AIRFLOW_CTX_TASK_ID='el_spotify' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T18:32:26.190012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T18:32:26.190012+00:00'
[2024-04-27T18:33:30.276+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T18:33:30.296+0000] {docker.py:359} INFO - Starting docker container from image meltano
[2024-04-27T18:33:30.297+0000] {docker.py:367} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-04-27T18:33:31.289+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:31.289022Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:33:31.414+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_id' was set in `.env`: (redacted)
[2024-04-27T18:33:33.554+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:33.554557Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:33:33.672+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_secret' was set in `.env`: (redacted)
[2024-04-27T18:33:35.864+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:35.864322Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:33:36.010+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'refresh_token' was set in `.env`: (redacted)
[2024-04-27T18:33:38.112+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:38.111903Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:33:38.239+0000] {docker.py:429} INFO - /venv/lib/python3.10/site-packages/meltano/cli/interactive/config.py:400: RuntimeWarning: Unknown setting ''
  value, metadata = settings.set_with_metadata(
[2024-04-27T18:33:38.240+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

not enough values to unpack (expected at least 1, got 0)
[2024-04-27T18:33:40.236+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:40.236094Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active[0m
[2024-04-27T18:33:41.696+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.696061Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,695 | INFO     | tap-spotify.global_top_tracks_daily_stream | Beginning full_table sync of 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:33:41.696+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.696636Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,695 | INFO     | tap-spotify.global_top_tracks_daily_stream | Tap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:33:41.931+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.930873Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,930 | INFO     | target-snowflake     | Target 'target-snowflake' is listening for input from tap.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.931+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.931273Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,931 | INFO     | target-snowflake     | Initializing 'target-snowflake' target sink...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.931+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.931494Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,931 | INFO     | target-snowflake.global_top_tracks_daily_stream | Initializing target sink for stream 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.938+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.938320Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,938 | INFO     | tap-spotify.global_top_tracks_daily_stream | OAuth authorization attempt was successful.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:33:41.947+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.947143Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:33:41,946 | INFO     | snowflake.connector.connection | Snowflake Connector for Python Version: 3.9.1, Python Version: 3.10.13, Platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.36[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.950+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.950635Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.951+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.950792Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.951+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.950939Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.951+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951121Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.951+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951263Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951404Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951526Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951641Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951760Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951870Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.951989Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.952+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952110Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.953+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952235Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.953+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952327Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.953+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952439Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.953+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952684Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.953+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952778Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.953+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952867Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.952953Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953051Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953141Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953235Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953328Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953419Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.954+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953508Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953596Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953688Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953778Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953875Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.953963Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954078Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954174Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954265Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954375Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954460Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954550Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954641Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954731Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.956+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954816Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954899Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.954982Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955072Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955163Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955253Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955342Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.957+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955437Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.958+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955528Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.958+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955621Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.958+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955715Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.958+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955806Z[0m [[32m[1minfo     [0m] [1msnowflake.connector.errors.ProgrammingError: 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.958+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.955908Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956020Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956120Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956216Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956314Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 8, in <module>[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956415Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetSnowflake.cli())[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956513Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956611Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.959+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956717Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956801Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956882Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 80, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.956963Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957045Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957170Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957266Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.960+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957349Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957431Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 567, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957514Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957596Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957677Z[0m [[32m[1minfo     [0m] [1m    self._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957758Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 307, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957839Z[0m [[32m[1minfo     [0m] [1m    counter = super()._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.957920Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 91, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.961+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958004Z[0m [[32m[1minfo     [0m] [1m    self._process_schema_message(line_dict)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958099Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 420, in _process_schema_message[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958193Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958295Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 792, in get_sink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958387Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958486Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 726, in add_sqlsink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958576Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958660Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/sinks.py", line 77, in setup[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958763Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958863Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 760, in prepare_schema[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.958957Z[0m [[32m[1minfo     [0m] [1m    schema_exists = self.schema_exists(schema_name)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959046Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 301, in schema_exists[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959137Z[0m [[32m[1minfo     [0m] [1m    schema_names = sqlalchemy.inspect(self._engine).get_schema_names()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959225Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 309, in _engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959317Z[0m [[32m[1minfo     [0m] [1m    self._cached_engine = self.create_engine()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.963+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959409Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 171, in create_engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959500Z[0m [[32m[1minfo     [0m] [1m    connection = engine.connect()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959592Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959685Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self, close_with_result=close_with_result)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959778Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959868Z[0m [[32m[1minfo     [0m] [1m    else engine.raw_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.959959Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960048Z[0m [[32m[1minfo     [0m] [1m    return self._wrap_pool_connect(self.pool.connect, _connection)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.964+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960142Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960235Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960329Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960427Z[0m [[32m[1minfo     [0m] [1m    util.raise_(              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960517Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960610Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960701Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.965+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960791Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960882Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.960973Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961065Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961157Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961248Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961339Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961431Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.966+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961522Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961613Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961700Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961789Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961880Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.961970Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962071Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962164Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.967+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962256Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962355Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962446Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962537Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962628Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962719Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962810Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.968+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962900Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.962986Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963070Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963160Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963250Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963341Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963431Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963523Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.969+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963617Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963707Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963799Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963890Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.963982Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964069Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964167Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.970+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964262Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964352Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964449Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964544Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964635Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964726Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964818Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964909Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.971+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.964999Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.972+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.965090Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:41.972+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:41.965188Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/14/f405)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:33:42.064+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:42.063767Z[0m [[31m[1merror    [0m] [1mLoader failed[0m
[2024-04-27T18:33:42.064+0000] {docker.py:429} INFO - [2m2024-04-27T18:33:42.063965Z[0m [[31m[1merror    [0m] [1mBlock run completed.          [0m [36mblock_type[0m=[35mExtractLoadBlocks[0m [36merr[0m=[35mRunnerError('Loader failed')[0m [36mexit_codes[0m=[35m{<PluginType.LOADERS: 'loaders'>: 1}[0m [36mset_number[0m=[35m0[0m [36msuccess[0m=[35mFalse[0m
[2024-04-27T18:33:42.065+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Loader failed
[2024-04-27T18:33:43.479+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T18:33:43.486+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 364, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmppv4vnodi")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 373, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-27T18:33:43.490+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_extract_dag, task_id=el_spotify, execution_date=20240427T183226, start_date=20240427T183330, end_date=20240427T183343
[2024-04-27T18:33:43.499+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 149 for task el_spotify (Docker container failed: {'StatusCode': 1}; 97)
[2024-04-27T18:33:43.535+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T18:33:43.549+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T18:33:43.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
