[2024-04-27T18:37:01.578+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T18:37:01.595+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:32:26.190012+00:00 [queued]>
[2024-04-27T18:37:01.599+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:32:26.190012+00:00 [queued]>
[2024-04-27T18:37:01.600+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 5
[2024-04-27T18:37:01.609+0000] {taskinstance.py:2327} INFO - Executing <Task(DockerOperator): el_spotify> on 2024-04-27 18:32:26.190012+00:00
[2024-04-27T18:37:01.614+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=140) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T18:37:01.615+0000] {standard_task_runner.py:63} INFO - Started process 141 to run task
[2024-04-27T18:37:01.616+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_extract_dag', 'el_spotify', 'manual__2024-04-27T18:32:26.190012+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/meltano_spotify_dag.py', '--cfg-path', '/tmp/tmpuf1ep9yk']
[2024-04-27T18:37:01.617+0000] {standard_task_runner.py:91} INFO - Job 150: Subtask el_spotify
[2024-04-27T18:37:01.647+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:32:26.190012+00:00 [running]> on host dab0fcf0ce12
[2024-04-27T18:37:01.712+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_extract_dag' AIRFLOW_CTX_TASK_ID='el_spotify' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T18:32:26.190012+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T18:32:26.190012+00:00'
[2024-04-27T18:37:01.712+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T18:37:01.732+0000] {docker.py:359} INFO - Starting docker container from image meltano
[2024-04-27T18:37:01.734+0000] {docker.py:367} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-04-27T18:37:02.694+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:02.694123Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:37:02.829+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_id' was set in `.env`: (redacted)
[2024-04-27T18:37:04.955+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:04.955576Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:37:05.082+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_secret' was set in `.env`: (redacted)
[2024-04-27T18:37:07.188+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:07.187804Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:37:07.314+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'refresh_token' was set in `.env`: (redacted)
[2024-04-27T18:37:09.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:09.351433Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:37:09.491+0000] {docker.py:429} INFO - /venv/lib/python3.10/site-packages/meltano/cli/interactive/config.py:400: RuntimeWarning: Unknown setting ''
  value, metadata = settings.set_with_metadata(
[2024-04-27T18:37:09.492+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

not enough values to unpack (expected at least 1, got 0)
[2024-04-27T18:37:11.597+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:11.597006Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active[0m
[2024-04-27T18:37:13.072+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.071965Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,071 | INFO     | tap-spotify.global_top_tracks_daily_stream | Beginning full_table sync of 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:37:13.073+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.072469Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,071 | INFO     | tap-spotify.global_top_tracks_daily_stream | Tap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:37:13.292+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.292158Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,291 | INFO     | tap-spotify.global_top_tracks_daily_stream | OAuth authorization attempt was successful.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:37:13.314+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.313741Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,313 | INFO     | target-snowflake     | Target 'target-snowflake' is listening for input from tap.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.314+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.314186Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,314 | INFO     | target-snowflake     | Initializing 'target-snowflake' target sink...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.314+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.314417Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,314 | INFO     | target-snowflake.global_top_tracks_daily_stream | Initializing target sink for stream 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.330+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.329738Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:37:13,329 | INFO     | snowflake.connector.connection | Snowflake Connector for Python Version: 3.9.1, Python Version: 3.10.13, Platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.36[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.332+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.332645Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.333+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.332801Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.333+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.332989Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.333+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333117Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.333+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333275Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.333+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333377Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.334+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333479Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.334+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333576Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.334+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333673Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.334+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333761Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.334+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333878Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.334+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.333960Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334069Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334148Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334223Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334455Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334536Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334611Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334685Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.335+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334758Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334832Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334907Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.334980Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335054Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335128Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335200Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.336+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335273Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335348Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335428Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335505Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335580Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335656Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335728Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335800Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.337+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335913Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.335994Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336070Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336143Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336215Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336288Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336361Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.338+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336434Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336507Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336579Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336651Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336730Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336805Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336878Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.339+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.336951Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337023Z[0m [[32m[1minfo     [0m] [1msnowflake.connector.errors.ProgrammingError: 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337095Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337168Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337239Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337311Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337382Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 8, in <module>[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.340+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337454Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetSnowflake.cli())[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337526Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337600Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337671Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337743Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337814Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 80, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337886Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.341+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.337957Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338028Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338106Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338181Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338253Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 567, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338341Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338414Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.342+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338490Z[0m [[32m[1minfo     [0m] [1m    self._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338564Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 307, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338637Z[0m [[32m[1minfo     [0m] [1m    counter = super()._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338711Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 91, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338785Z[0m [[32m[1minfo     [0m] [1m    self._process_schema_message(line_dict)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338858Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 420, in _process_schema_message[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.338931Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.343+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339003Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 792, in get_sink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339076Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339149Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 726, in add_sqlsink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339223Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339297Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/sinks.py", line 77, in setup[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339376Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339450Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 760, in prepare_schema[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.344+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339523Z[0m [[32m[1minfo     [0m] [1m    schema_exists = self.schema_exists(schema_name)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339615Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 301, in schema_exists[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339708Z[0m [[32m[1minfo     [0m] [1m    schema_names = sqlalchemy.inspect(self._engine).get_schema_names()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339841Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 309, in _engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.339955Z[0m [[32m[1minfo     [0m] [1m    self._cached_engine = self.create_engine()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340034Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 171, in create_engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340127Z[0m [[32m[1minfo     [0m] [1m    connection = engine.connect()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340207Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.345+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340280Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self, close_with_result=close_with_result)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340352Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340425Z[0m [[32m[1minfo     [0m] [1m    else engine.raw_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340499Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340573Z[0m [[32m[1minfo     [0m] [1m    return self._wrap_pool_connect(self.pool.connect, _connection)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340646Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340719Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340793Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340872Z[0m [[32m[1minfo     [0m] [1m    util.raise_(              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.340947Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341026Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341100Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341173Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341246Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341318Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341391Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.347+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341463Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341535Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341607Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341679Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341751Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341825Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341899Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.348+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.341972Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342044Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342115Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342192Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342274Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342356Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342431Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342505Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.349+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342577Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342648Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342720Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342794Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342866Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.342938Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343010Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343083Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.350+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343156Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343227Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343299Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343372Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343452Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343527Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343599Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.351+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343671Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343743Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343814Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343887Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.343959Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344030Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344103Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344176Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.352+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344250Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.353+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344325Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.353+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344398Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.353+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344471Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.353+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344544Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.353+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344618Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.353+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.344699Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/14/f405)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:37:13.447+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.447413Z[0m [[31m[1merror    [0m] [1mLoader failed[0m
[2024-04-27T18:37:13.448+0000] {docker.py:429} INFO - [2m2024-04-27T18:37:13.447648Z[0m [[31m[1merror    [0m] [1mBlock run completed.          [0m [36mblock_type[0m=[35mExtractLoadBlocks[0m [36merr[0m=[35mRunnerError('Loader failed')[0m [36mexit_codes[0m=[35m{<PluginType.LOADERS: 'loaders'>: 1}[0m [36mset_number[0m=[35m0[0m [36msuccess[0m=[35mFalse[0m
[2024-04-27T18:37:13.448+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Loader failed
[2024-04-27T18:37:14.835+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T18:37:14.842+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 364, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpajxyj66y")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 373, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-27T18:37:14.846+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_extract_dag, task_id=el_spotify, execution_date=20240427T183226, start_date=20240427T183701, end_date=20240427T183714
[2024-04-27T18:37:14.854+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 150 for task el_spotify (Docker container failed: {'StatusCode': 1}; 141)
[2024-04-27T18:37:14.879+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T18:37:14.893+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T18:37:14.895+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
