[2024-04-27T18:27:39.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T18:27:39.289+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:13:40.687152+00:00 [queued]>
[2024-04-27T18:27:39.295+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:13:40.687152+00:00 [queued]>
[2024-04-27T18:27:39.295+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 7
[2024-04-27T18:27:39.305+0000] {taskinstance.py:2327} INFO - Executing <Task(DockerOperator): el_spotify> on 2024-04-27 18:13:40.687152+00:00
[2024-04-27T18:27:39.311+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T18:27:39.312+0000] {standard_task_runner.py:63} INFO - Started process 270 to run task
[2024-04-27T18:27:39.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_extract_dag', 'el_spotify', 'manual__2024-04-27T18:13:40.687152+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/meltano_spotify_dag.py', '--cfg-path', '/tmp/tmp5zuh1xk3']
[2024-04-27T18:27:39.314+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask el_spotify
[2024-04-27T18:27:39.342+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:13:40.687152+00:00 [running]> on host c98a6e68ea8f
[2024-04-27T18:27:39.406+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_extract_dag' AIRFLOW_CTX_TASK_ID='el_spotify' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T18:13:40.687152+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T18:13:40.687152+00:00'
[2024-04-27T18:27:39.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T18:27:39.426+0000] {docker.py:359} INFO - Starting docker container from image meltano
[2024-04-27T18:27:39.428+0000] {docker.py:367} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-04-27T18:27:40.346+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:40.345247Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:27:40.465+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_id' was set in `.env`: (redacted)
[2024-04-27T18:27:42.582+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:42.582525Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:27:42.702+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_secret' was set in `.env`: (redacted)
[2024-04-27T18:27:44.691+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:44.690963Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:27:44.813+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'refresh_token' was set in `.env`: (redacted)
[2024-04-27T18:27:46.841+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:46.841275Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:27:46.967+0000] {docker.py:429} INFO - /venv/lib/python3.10/site-packages/meltano/cli/interactive/config.py:400: RuntimeWarning: Unknown setting ''
  value, metadata = settings.set_with_metadata(
[2024-04-27T18:27:46.967+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

not enough values to unpack (expected at least 1, got 0)
[2024-04-27T18:27:48.962+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:48.962014Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active[0m
[2024-04-27T18:27:50.369+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.368979Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,368 | INFO     | tap-spotify.global_top_tracks_daily_stream | Beginning full_table sync of 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:27:50.369+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.369429Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,368 | INFO     | tap-spotify.global_top_tracks_daily_stream | Tap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:27:50.580+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.580095Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,579 | INFO     | tap-spotify.global_top_tracks_daily_stream | OAuth authorization attempt was successful.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:27:50.599+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.598893Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,598 | INFO     | target-snowflake     | Target 'target-snowflake' is listening for input from tap.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.599+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.599152Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,598 | INFO     | target-snowflake     | Initializing 'target-snowflake' target sink...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.599+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.599306Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,598 | INFO     | target-snowflake.global_top_tracks_daily_stream | Initializing target sink for stream 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.615+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.615016Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:27:50,614 | INFO     | snowflake.connector.connection | Snowflake Connector for Python Version: 3.9.1, Python Version: 3.10.13, Platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.36[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.617+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.617264Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.617+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.617401Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.618+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.617574Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.618+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.617700Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.618+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.617864Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.618+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.617967Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.618+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618073Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.618+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618174Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618281Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618382Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618511Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618593Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618668Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618741Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.619+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.618953Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619029Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619102Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619175Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619249Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619322Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619395Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.620+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619468Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619540Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619611Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619684Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619756Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619828Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619900Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.621+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.619979Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620053Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620144Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620221Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620319Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620396Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620478Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.622+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620551Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620625Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620699Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620773Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620846Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620918Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.620990Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621063Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.623+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621136Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621208Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621288Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621363Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621436Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621508Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621581Z[0m [[32m[1minfo     [0m] [1msnowflake.connector.errors.ProgrammingError: 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.624+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621654Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621727Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621799Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621871Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.621943Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 8, in <module>[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622015Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetSnowflake.cli())[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622087Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.625+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622160Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622233Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622321Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622394Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 80, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622467Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622540Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622612Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.626+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622691Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622767Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622840Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 567, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622913Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.622999Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623072Z[0m [[32m[1minfo     [0m] [1m    self._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623144Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 307, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623218Z[0m [[32m[1minfo     [0m] [1m    counter = super()._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.627+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623291Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 91, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623363Z[0m [[32m[1minfo     [0m] [1m    self._process_schema_message(line_dict)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623436Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 420, in _process_schema_message[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623508Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623581Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 792, in get_sink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623653Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623725Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 726, in add_sqlsink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.628+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623798Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623871Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/sinks.py", line 77, in setup[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.623949Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624024Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 760, in prepare_schema[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624131Z[0m [[32m[1minfo     [0m] [1m    schema_exists = self.schema_exists(schema_name)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624212Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 301, in schema_exists[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624286Z[0m [[32m[1minfo     [0m] [1m    schema_names = sqlalchemy.inspect(self._engine).get_schema_names()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624360Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 309, in _engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.629+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624432Z[0m [[32m[1minfo     [0m] [1m    self._cached_engine = self.create_engine()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624504Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 171, in create_engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624576Z[0m [[32m[1minfo     [0m] [1m    connection = engine.connect()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624654Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624734Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self, close_with_result=close_with_result)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624817Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624897Z[0m [[32m[1minfo     [0m] [1m    else engine.raw_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.624980Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.630+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625053Z[0m [[32m[1minfo     [0m] [1m    return self._wrap_pool_connect(self.pool.connect, _connection)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625125Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625211Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625284Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625369Z[0m [[32m[1minfo     [0m] [1m    util.raise_(              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625456Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625530Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.631+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625603Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625675Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625747Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625819Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625890Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.625962Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626034Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626106Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626178Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.632+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626250Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626331Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626403Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626475Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626548Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626621Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626697Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.633+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626772Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626844Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626916Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.626989Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627061Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627133Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627205Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627280Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.634+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627352Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627424Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627497Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627570Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627642Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627713Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627786Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627860Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.635+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.627939Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628015Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628089Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628161Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628234Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628306Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628377Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628449Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.636+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628521Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628594Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628666Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628739Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628811Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628883Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.628957Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.637+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.629030Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.638+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.629103Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.638+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.629183Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/14/f405)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:27:50.722+0000] {docker.py:429} INFO - [2m2024-04-27T18:27:50.721576Z[0m [[31m[1merror    [0m] [1mLoader failed[0m
[2m2024-04-27T18:27:50.721727Z[0m [[31m[1merror    [0m] [1mBlock run completed.          [0m [36mblock_type[0m=[35mExtractLoadBlocks[0m [36merr[0m=[35mRunnerError('Loader failed')[0m [36mexit_codes[0m=[35m{<PluginType.LOADERS: 'loaders'>: 1}[0m [36mset_number[0m=[35m0[0m [36msuccess[0m=[35mFalse[0m
[2024-04-27T18:27:50.722+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Loader failed
[2024-04-27T18:27:52.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T18:27:52.061+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 364, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpyfefmug2")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 373, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-27T18:27:52.065+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_extract_dag, task_id=el_spotify, execution_date=20240427T181340, start_date=20240427T182739, end_date=20240427T182752
[2024-04-27T18:27:52.074+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 143 for task el_spotify (Docker container failed: {'StatusCode': 1}; 270)
[2024-04-27T18:27:52.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T18:27:52.128+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T18:27:52.130+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
