[2024-04-27T18:22:25.091+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T18:22:25.108+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:13:40.687152+00:00 [queued]>
[2024-04-27T18:22:25.113+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:13:40.687152+00:00 [queued]>
[2024-04-27T18:22:25.114+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 7
[2024-04-27T18:22:25.122+0000] {taskinstance.py:2327} INFO - Executing <Task(DockerOperator): el_spotify> on 2024-04-27 18:13:40.687152+00:00
[2024-04-27T18:22:25.128+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T18:22:25.128+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2024-04-27T18:22:25.129+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_extract_dag', 'el_spotify', 'manual__2024-04-27T18:13:40.687152+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/meltano_spotify_dag.py', '--cfg-path', '/tmp/tmpgaouh957']
[2024-04-27T18:22:25.130+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask el_spotify
[2024-04-27T18:22:25.161+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_extract_dag.el_spotify manual__2024-04-27T18:13:40.687152+00:00 [running]> on host c98a6e68ea8f
[2024-04-27T18:22:25.225+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_extract_dag' AIRFLOW_CTX_TASK_ID='el_spotify' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T18:13:40.687152+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T18:13:40.687152+00:00'
[2024-04-27T18:22:25.226+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T18:22:25.246+0000] {docker.py:359} INFO - Starting docker container from image meltano
[2024-04-27T18:22:25.248+0000] {docker.py:367} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-04-27T18:22:26.165+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:26.164762Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:22:26.286+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_id' was set in `.env`: (redacted)
[2024-04-27T18:22:28.484+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:28.484375Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:22:28.603+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'client_secret' was set in `.env`: (redacted)
[2024-04-27T18:22:30.695+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:30.694633Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:22:30.820+0000] {docker.py:429} INFO - Extractor 'tap-spotify' setting 'refresh_token' was set in `.env`: (redacted)
[2024-04-27T18:22:32.894+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:32.894330Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2024-04-27T18:22:33.027+0000] {docker.py:429} INFO - /venv/lib/python3.10/site-packages/meltano/cli/interactive/config.py:400: RuntimeWarning: Unknown setting ''
  value, metadata = settings.set_with_metadata(
[2024-04-27T18:22:33.027+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

not enough values to unpack (expected at least 1, got 0)
[2024-04-27T18:22:35.068+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:35.068211Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active[0m
[2024-04-27T18:22:36.731+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:36.731335Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:36,731 | INFO     | tap-spotify.global_top_tracks_daily_stream | Beginning full_table sync of 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:22:36.732+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:36.731756Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:36,731 | INFO     | tap-spotify.global_top_tracks_daily_stream | Tap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:22:37.004+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.003840Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:37,003 | INFO     | tap-spotify.global_top_tracks_daily_stream | OAuth authorization attempt was successful.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mFalse[0m [36mname[0m=[35mtap-spotify[0m [36mproducer[0m=[35mTrue[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtap-spotify[0m
[2024-04-27T18:22:37.226+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.226161Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:37,225 | INFO     | target-snowflake     | Target 'target-snowflake' is listening for input from tap.[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.227+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.226643Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:37,226 | INFO     | target-snowflake     | Initializing 'target-snowflake' target sink...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.227+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.226831Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:37,226 | INFO     | target-snowflake.global_top_tracks_daily_stream | Initializing target sink for stream 'global_top_tracks_daily_stream'...[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.244+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.244090Z[0m [[32m[1minfo     [0m] [1m2024-04-27 18:22:37,243 | INFO     | snowflake.connector.connection | Snowflake Connector for Python Version: 3.9.1, Python Version: 3.10.13, Platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.36[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.254+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254127Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.254+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254327Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.254+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254511Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.255+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254623Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.255+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254773Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.255+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254872Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.255+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.254954Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.255+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255026Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.255+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255100Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255173Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255288Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255369Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255445Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255519Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255657Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.256+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255741Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.255986Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256067Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256142Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256215Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256289Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256363Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.257+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256436Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.258+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256511Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.258+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256585Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.258+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256658Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.258+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256758Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.258+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256836Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.258+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256916Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.259+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.256992Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.259+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257064Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.259+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257137Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.259+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257209Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.259+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257281Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.259+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257354Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257428Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257503Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257577Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257651Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257724Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257798Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.260+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257872Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.257975Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258054Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258129Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258208Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258292Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258372Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.261+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258445Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258517Z[0m [[32m[1minfo     [0m] [1msnowflake.connector.errors.ProgrammingError: 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258588Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258660Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258745Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258825Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258905Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 8, in <module>[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.262+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.258987Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetSnowflake.cli())[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259068Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259147Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259220Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259293Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259366Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 80, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259440Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.263+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259514Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259588Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259668Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259743Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259831Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 567, in invoke[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259905Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.259979Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.264+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260059Z[0m [[32m[1minfo     [0m] [1m    self._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260139Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 307, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260212Z[0m [[32m[1minfo     [0m] [1m    counter = super()._process_lines(file_input)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260287Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 91, in _process_lines[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260362Z[0m [[32m[1minfo     [0m] [1m    self._process_schema_message(line_dict)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260436Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 420, in _process_schema_message[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260546Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.265+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260627Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 792, in get_sink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260703Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260778Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 726, in add_sqlsink[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260853Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.260927Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/sinks.py", line 77, in setup[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261008Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261085Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 760, in prepare_schema[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.266+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261159Z[0m [[32m[1minfo     [0m] [1m    schema_exists = self.schema_exists(schema_name)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261233Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 301, in schema_exists[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261306Z[0m [[32m[1minfo     [0m] [1m    schema_names = sqlalchemy.inspect(self._engine).get_schema_names()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261379Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 309, in _engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261451Z[0m [[32m[1minfo     [0m] [1m    self._cached_engine = self.create_engine()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261524Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/connector.py", line 171, in create_engine[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261597Z[0m [[32m[1minfo     [0m] [1m    connection = engine.connect()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261669Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.267+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261743Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self, close_with_result=close_with_result)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261816Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261889Z[0m [[32m[1minfo     [0m] [1m    else engine.raw_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.261962Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262035Z[0m [[32m[1minfo     [0m] [1m    return self._wrap_pool_connect(self.pool.connect, _connection)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262108Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262181Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262254Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.268+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262344Z[0m [[32m[1minfo     [0m] [1m    util.raise_(              [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262420Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262494Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262573Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262648Z[0m [[32m[1minfo     [0m] [1m    return fn()               [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262721Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262794Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262869Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.269+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.262943Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263016Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263088Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263161Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263234Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263325Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263427Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263504Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.270+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263579Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263652Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263731Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263806Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263880Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.263953Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264025Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264098Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.271+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264171Z[0m [[32m[1minfo     [0m] [1m    with util.safe_reraise(): [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264244Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264316Z[0m [[32m[1minfo     [0m] [1m    compat.raise_(            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264388Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264461Z[0m [[32m[1minfo     [0m] [1m    raise exception           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264534Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264607Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264680Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.272+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264752Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264825Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/snowdialect.py", line 892, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264898Z[0m [[32m[1minfo     [0m] [1m    super().connect(          [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.264977Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265053Z[0m [[32m[1minfo     [0m] [1m    return self.dbapi.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265126Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 55, in Connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265199Z[0m [[32m[1minfo     [0m] [1m    return SnowflakeConnection(**kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265271Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 442, in __init__[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.273+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265343Z[0m [[32m[1minfo     [0m] [1m    self.connect(**kwargs)    [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265416Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 707, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265489Z[0m [[32m[1minfo     [0m] [1m    self.__config(**kwargs)   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265562Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1208, in __config[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265634Z[0m [[32m[1minfo     [0m] [1m    Error.errorhandler_wrapper([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265706Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265779Z[0m [[32m[1minfo     [0m] [1m    handed_over = Error.hand_to_other_handler([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265852Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.274+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265925Z[0m [[32m[1minfo     [0m] [1m    connection.errorhandler(connection, cursor, error_class, error_value)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.275+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.265998Z[0m [[32m[1minfo     [0m] [1m  File "/project/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.275+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.266070Z[0m [[32m[1minfo     [0m] [1m    raise error_class(        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.275+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.266143Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 251006: 251006: Password is empty[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.275+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.266221Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/14/f405)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mname[0m=[35mtarget-snowflake[0m [36mproducer[0m=[35mFalse[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-snowflake[0m
[2024-04-27T18:22:37.359+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.359532Z[0m [[31m[1merror    [0m] [1mLoader failed[0m
[2024-04-27T18:22:37.360+0000] {docker.py:429} INFO - [2m2024-04-27T18:22:37.359775Z[0m [[31m[1merror    [0m] [1mBlock run completed.          [0m [36mblock_type[0m=[35mExtractLoadBlocks[0m [36merr[0m=[35mRunnerError('Loader failed')[0m [36mexit_codes[0m=[35m{<PluginType.LOADERS: 'loaders'>: 1}[0m [36mset_number[0m=[35m0[0m [36msuccess[0m=[35mFalse[0m
[2024-04-27T18:22:37.360+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Loader failed
[2024-04-27T18:22:38.695+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T18:22:38.703+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 364, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmp2wywl32u")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 373, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-27T18:22:38.707+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_extract_dag, task_id=el_spotify, execution_date=20240427T181340, start_date=20240427T182225, end_date=20240427T182238
[2024-04-27T18:22:38.717+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 142 for task el_spotify (Docker container failed: {'StatusCode': 1}; 198)
[2024-04-27T18:22:38.761+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T18:22:38.774+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T18:22:38.776+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
